from setuptools import setup, find_packages

setup(
    name="melotts",
    version="2.1.0",
    packages=find_packages(),
    install_requires=[
        "torch",
        "torchaudio",
        "numpy",
        "librosa",
        "soundfile",
        "tqdm",
        "click",
        "transformers",
        "cn2an",
        "pypinyin",
        "jieba",
        "inflect",
        "unidecode",
        "phonemizer",
        "ko_pron",
        "gruut[de,es,fr]",
        "eng_to_ipa",
        "pyopenjtalk",
        "mecab-python3",
        "unidic-lite",
        "pykakasi",
        "fugashi",
        "ipadic",
        "g2p_en",
        "jamo",
        "cached-path"
    ],
    author="MeloTTS Team",
    description="A text-to-speech synthesis package",
    python_requires=">=3.7",
    include_package_data=True,
)
